### ISSUE TITLE
Необходимо поставить эмодзи на шаги паиплаина сборки контейнера

### ISSUE THREAD

**Issue by shpaker** [qqalexqq/tgforwarderclient#5]
https://github.com/qqalexqq/tgforwarderclient/blob/main/.github/workflows/build.yml

по образу и подобию как здесь https://github.com/qqalexqq/tgforwarderclient/blob/main/.github/workflows/deploy.yml

**Comment by qqalexqq** [comment]
Checkout https://github.com/qqalexqq/tgforwarderclient/pull/10
